name: PHP Lint

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # WP themes often support older versions
          tools: php-parallel-lint

      - name: PHP Lint
        run: parallel-lint . --exclude vendor --exclude .github
